site_name: ""


nav:
  - "▸ <img src='https://arudoon.github.io/MkDocs_Dokumentasi/assets/icons/home.png' style='width:50px; vertical-align:middle;'> ◂": index.md
  - "▸ <img src='https://arudoon.github.io/MkDocs_Dokumentasi/assets/icons/setup.png' style='width:58px; vertical-align:middle;'> ◂": 2-setup.md
  - "▸ <img src='https://arudoon.github.io/MkDocs_Dokumentasi/assets/icons/software.png' style='width:100px; vertical-align:middle;'> ◂": 3-instalasiSoftware.md
  - "▸ <img src='https://arudoon.github.io/MkDocs_Dokumentasi/assets/icons/vision.png' style='width:60px; vertical-align:middle;'> ◂": 4-instalasiVision.md
  - "▸ <img src='https://arudoon.github.io/MkDocs_Dokumentasi/assets/icons/simulation-3.png' style='width:115px; vertical-align:middle;'> ◂": 5-simulation.md



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details



theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: fontawesome/brands/windows
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: fontawesome/brands/linux
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  font:
    code: Red Hat Mono
  
  logo: https://arudoon.github.io/MkDocs_Dokumentasi/assets/icons/barelangf1white.png
  favicon: assets/pictures/F1Maskot.png

  palette: 
    scheme: slate
    primary: red
    accent: light green


extra:
  annotate:
    json: [.s2]


extra_css:
  - css/intro.css 
  - css/easter-egg.css


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js
  # - js/blur-transition.js
  - js/intro.js
  - js/easter-egg.js


## Login screen (comment out to disable)
#extra_javascript:
  #- assets/js/auth.js
#extra_css:
  #- assets/css/login.css


# === SITE SCONSISTENCY SETINGS (IDK INI PENGARUH BANGET OR WUT BUT JUST LEAVE IT AS IT IS) ===
docs_dir: source
site_dir: docs
site_url: https://arudoon.github.io/MkDocs_Dokumentasi/